# Generated by Django 4.2.1 on 2023-05-25 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paystub1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period_start', models.DateField()),
                ('pay_period_end', models.DateField()),
                ('gross_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_earnings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_tax_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('federal_income_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state_income_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_tax_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='PayStub',
        ),
    ]
